{
  "openapi": "3.0.0",
  "paths": {
    "/v1/environments/vc-request/callbacks": {
      "get": {
        "operationId": "VCCallbackController_getCallback",
        "summary": "Get vc issuance callback environments",
        "description": "등록된 VC 발급 요청 콜백 정보를 조회합니다.",
        "parameters": [],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VCCallbackResponseDTO" } }
                }
              }
            }
          }
        },
        "tags": ["Environments setting"]
      },
      "post": {
        "operationId": "VCCallbackController_updateCallback",
        "summary": "Update vc issuance callback environments",
        "description": "VC 발급 요청 콜백 정보를 수정합니다.",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/VCCallbackRequestDTO" } } }
        },
        "responses": { "204": { "description": "The request was successful. but there is no content to send" } },
        "tags": ["Environments setting"]
      }
    },
    "/v1/environments/vc-requests/templates": {
      "get": {
        "operationId": "VCTemplateController_getVCTemplates",
        "summary": "Get VC Templates",
        "description": "VC 템플릿 목록을 가져옵니다. 검색 혹은 정렬하여 가져올 수도 있습니다",
        "parameters": [
          {
            "name": "search",
            "required": false,
            "in": "query",
            "description": "VC 템플릿 검색어. VC의 타입, 템플릿 제목이나 설명 그리고 VC 속성의 이름에 대해 검색합니다.",
            "schema": { "type": "string" }
          },
          {
            "name": "sortBy",
            "required": false,
            "in": "query",
            "description": "VC 템플릿 정렬 기준",
            "schema": { "enum": ["name", "createAt"], "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VCTemplatesResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC templates"]
      },
      "put": {
        "operationId": "VCTemplateController_createVCTemplates",
        "summary": "Create VC Templates",
        "description": "VC 발급을 위한 템플릿을 생성합니다. 최초 VC를 발급 한 후 템플릿은 수정/삭제할 수 없습니다.",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/CreateVCTemplateRequestDTO" } } }
        },
        "responses": {
          "201": {
            "description": "The resource was created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/CreateVCTemplateResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC templates"]
      }
    },
    "/v1/environments/vc-requests/templates/{id}": {
      "get": {
        "operationId": "VCTemplateController_getVCTemplate",
        "summary": "Get VC Template by id",
        "description": "지정한 식별자에 해당하는 VC템플릿의 상세한 정보를 가져옵니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VC템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VCTemplateResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC templates"]
      },
      "post": {
        "operationId": "VCTemplateController_updateVCTemplate",
        "summary": "Update VC Template",
        "description": "지정한 식별자에 해당하는 VC 미발급된 VC템플릿의 정보를 수정합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VC템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/UpdateVCTemplateRequestDTO" } } }
        },
        "responses": {
          "204": { "description": "The request was successful. but there is no content to send" },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC templates"]
      },
      "delete": {
        "operationId": "VCTemplateController_deleteVCTemplate",
        "summary": "Delete VC Template",
        "description": "지정한 식별자에 해당하는 VC 미발급된 VC템플릿을 삭제합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VC템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "204": { "description": "The request was successful. but there is no content to send" },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC templates"]
      }
    },
    "/v1/environments/vp-responses/templates": {
      "get": {
        "operationId": "VPTemplateController_getVCTemplates",
        "summary": "Get VP Templates",
        "description": "VP 검증 템플릿 목록을 가져옵니다. 검색 혹은 정렬하여 가져올 수도 있습니다",
        "parameters": [
          {
            "name": "search",
            "required": false,
            "in": "query",
            "description": "VP 템플릿 검색어. 템플릿 제목이나 설명 그리고 포함된 VC의 타에 대해 검색합니다.",
            "schema": { "type": "string" }
          },
          {
            "name": "sortBy",
            "required": false,
            "in": "query",
            "description": "VP 템플릿 정렬 기준",
            "schema": { "enum": ["name", "createAt"], "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VPTemplatesResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VP templates"]
      },
      "put": {
        "operationId": "VPTemplateController_createVCTemplates",
        "summary": "Create VP Templates",
        "description": "VP 검증 템플릿을 생성합니다.",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/CreateVPTemplateRequestDTO" } } }
        },
        "responses": {
          "201": {
            "description": "The resource was created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/CreateVPTemplateResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VP templates"]
      }
    },
    "/v1/environments/vp-responses/templates/{id}": {
      "get": {
        "operationId": "VPTemplateController_getVPTemplate",
        "summary": "Get VP Template by id",
        "description": "지정한 식별자에 해당하는 VP 템플릿의 상세한 정보를 가져옵니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VP 템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VPTemplateResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VP templates"]
      },
      "post": {
        "operationId": "VPTemplateController_updateVCTemplate",
        "summary": "Update VP Template",
        "description": "지정한 식별자에 해당하는 VP 템플릿의 정보를 수정합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VP 템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/UpdateVPTemplateRequestDTO" } } }
        },
        "responses": {
          "204": { "description": "The request was successful. but there is no content to send" },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VP templates"]
      },
      "delete": {
        "operationId": "VPTemplateController_deleteVPTemplate",
        "summary": "Delete VP Template",
        "description": "지정한 식별자에 해당하는VP 템플릿을 삭제합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VP 템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "204": { "description": "The request was successful. but there is no content to send" },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VP templates"]
      }
    },
    "/v1/vcs/requests": {
      "get": {
        "operationId": "VCRequestsController_getVCIssuanceRequestList",
        "summary": "Get VC Issuance Request list",
        "description": " VC 발급 요청 목록을 가져옵니다. 요청의 상태와 holder(VC 발급 요청자)의 DID로 검색하여 가져올 수도 있습니다. \n\n        holder: 자신이 생성한 VC 요청 \n\n        issuer: 요청받은 VC 요청",
        "parameters": [
          {
            "name": "status",
            "required": false,
            "in": "query",
            "description": "발급 요청의 상태 값",
            "example": "Pending",
            "schema": { "enum": ["Approved", "Rejected", "Pending"], "type": "string" }
          },
          {
            "name": "vcTemplateId",
            "required": false,
            "in": "query",
            "description": "VC 템플릿의 식별자",
            "example": "625844c8-8265-4264-8e64-7c5c40f54b77",
            "schema": { "type": "string" }
          },
          {
            "name": "holderDID",
            "required": false,
            "in": "query",
            "description": "Holder(VC 발급 요청자)의 DID",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VCRequestsResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC Issuance Request"]
      },
      "post": {
        "operationId": "VCRequestsController_createVcIssuanceRequest",
        "summary": "Create VC Issuance Request",
        "description": "holder: VC 템플릿을 지정하여, VC 발급을 요청합니다.",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "schema": { "$ref": "#/components/schemas/CreateRequestVCIssuanceRequestDTO" } }
          }
        },
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/CreateRequestVCIssuanceResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC Issuance Request"]
      }
    },
    "/v1/vcs/requests/{id}": {
      "get": {
        "operationId": "VCRequestsController_getVCIssuanceRequest",
        "summary": "Get VC Issuance Request",
        "description": "VC 요청의 식별자를 이용하여 상세 정보를 조회합니다. \n\n        holder: 자신이 생성한 VC 요청 \n \n        issuer: 요청받은 VC 요청",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VC요청의 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VCRequestResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC Issuance Request"]
      },
      "post": {
        "operationId": "VCRequestsController_vcIssuanceResponse",
        "summary": "Issue/Reject Requested VC",
        "description": "issuer: 지정된 VC요청 식별자에 해당하는 VC발급 요청을 수락/거절 합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VC요청의 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": { "application/json": { "schema": { "$ref": "#/components/schemas/VCIssuanceRequestDTO" } } }
        },
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/VCIssuanceResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC Issuance Request"]
      },
      "delete": {
        "operationId": "VCRequestsController_deleteVcIssuanceRequest",
        "summary": "Cancel VC Issuance Request",
        "description": "holder: 지정한 VC요청 식별자에 해당하는 VC발급 요청을 취소합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "VC요청의 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "204": { "description": "The request was successful. but there is no content to send" },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VC Issuance Request"]
      }
    },
    "/v1/vcs": {
      "get": {
        "operationId": "VCController_getIssuedVCList",
        "summary": "Get Issued VC List",
        "description": "발급된 VC의 목록을 조회합니다. Holder의 DID(issuer) 혹은 VC 템플릿의 식별값으로 검색하여 가져올 수도 있습니다.\n\n        holder: 자신이 발급받은 VC 목록\n\n        issuer: 자신이 발급한 VC 목록",
        "parameters": [
          {
            "name": "holderDID",
            "required": false,
            "in": "query",
            "description": "VC holder의 DID",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH",
            "schema": { "type": "string" }
          },
          {
            "name": "vcTemplateId",
            "required": false,
            "in": "query",
            "description": "VC 템플릿의 식별자",
            "example": "did:infra:space:5GUHm8KeFXUKBR9kctm3eafs2tgqK3XxcqsnHtRp2kjSdfDF",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/IssuedVCsResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VCS"]
      }
    },
    "/v1/vcs/{id}": {
      "get": {
        "operationId": "VCController_getIssuedVC",
        "summary": "Get Issued VC List",
        "description": "지정한 식별자를 통해 발급된 VC의 상세 정보를 조회합니다.\n\n        holder: 자신이 발급받은 VC\n\n        issuer: 자신이 발급한 VC",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "발급된 VC의 식별자",
            "example": "did:infra:space:5GUHm8KeFXUKBR9kctm3eafs2tgqK3XxcqsnHtRp2kjSdfDF",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "The request was successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": { "result": { "$ref": "#/components/schemas/IssuedVCResponseDTO" } }
                }
              }
            }
          },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VCS"]
      }
    },
    "/v1/vcs/revoke/{id}": {
      "post": {
        "operationId": "VCController_revokeIssuedVC",
        "summary": "Revoke Issued VC",
        "description": "issuer: 지정한 식별자에 해당하는 VC를 폐기(revoke) 합니다.",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "발급된 VC의 식별자",
            "example": "did:infra:space:5GUHm8KeFXUKBR9kctm3eafs2tgqK3XxcqsnHtRp2kjSdfDF",
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "204": { "description": "The request was successful. but there is no content to send" },
          "400": { "description": "The request is not valid" },
          "401": { "description": "Authentication failed" },
          "403": { "description": "The server understands the request but refuses to authorize it." },
          "500": { "description": "An unexpected error occurred inside the server" }
        },
        "tags": ["VCS"]
      }
    }
  },
  "info": { "title": "IWS Cert Server API", "description": "", "version": "0.1", "contact": {} },
  "tags": [],
  "servers": [],
  "components": {
    "schemas": {
      "MetaData": { "type": "object", "properties": {} },
      "VCCallbackResponseDTO": {
        "type": "object",
        "properties": {
          "callbackUrl": {
            "type": "string",
            "description": "VC 발급 요청 확인을 위해 콜백을 전달 받을 서비스 서버의 url",
            "example": "https://www.pet-i.net/vc/request/callback"
          },
          "sharedMetaData": {
            "description": "VC 발급을 위해 사용자가 공통적으로 제출해야하는 메타 데이터",
            "example": { "name": "max", "ci": "12834792343" },
            "allOf": [{ "$ref": "#/components/schemas/MetaData" }]
          },
          "createdAt": { "type": "string", "description": "생성 일시", "example": "2023-03-27T23:50:40.465Z" },
          "updatedAt": { "type": "string", "description": "마지막 수정 일시", "example": "2023-03-27T23:50:40.465Z" }
        },
        "required": ["callbackUrl", "sharedMetaData", "createdAt", "updatedAt"]
      },
      "VCCallbackRequestDTO": {
        "type": "object",
        "properties": {
          "callbackUrl": {
            "type": "string",
            "description": "VC 발급 요청 확인을 위해 콜백을 전달 받을 서비스 서버의 url",
            "example": "https://www.pet-i.net/vc/request/callback"
          },
          "sharedMetaData": {
            "description": "VC 발급을 위해 사용자가 공통적으로 제출해야하는 메타 데이터",
            "example": { "name": "max", "ci": "12834792343" },
            "allOf": [{ "$ref": "#/components/schemas/MetaData" }]
          }
        },
        "required": ["callbackUrl", "sharedMetaData"]
      },
      "VCTemplatesItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "VC템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "credentialType": {
            "type": "string",
            "description": "템플릿에 지정된 VC 타입",
            "example": "VaccinationCredential"
          },
          "isModifiable": { "type": "boolean", "description": "템플릿 수정 가능 여부(VC 발급 여부)", "example": true }
        },
        "required": ["id", "credentialType", "isModifiable"]
      },
      "VCTemplatesResponseDTO": {
        "type": "object",
        "properties": {
          "templates": {
            "description": "VC 템플릿의 목록",
            "example": [
              {
                "id": "849e1786-b4e9-407e-8d0d-86777770af8a",
                "credentialType": "VaccinationCredential",
                "isModifiable": true
              }
            ],
            "type": "array",
            "items": { "$ref": "#/components/schemas/VCTemplatesItem" }
          }
        },
        "required": ["templates"]
      },
      "CreateVCTemplateResponseDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "VC템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          }
        },
        "required": ["id"]
      },
      "MetaDataItem": {
        "type": "object",
        "properties": {
          "key": { "type": "string", "description": "발급할 VC의 Claim key 값", "example": "email" },
          "type": { "type": "string", "description": "발급할 VC의 Claim key의 타입", "example": "string" },
          "properties": {
            "description": "object type에 대한 claim key, type 지정",
            "example": { "properties": { "a": { "type": "string" } } },
            "allOf": [{ "$ref": "#/components/schemas/MetaDataItem" }]
          }
        },
        "required": ["key", "type"]
      },
      "CreateVCTemplateRequestDTO": {
        "type": "object",
        "properties": {
          "credentialType": {
            "type": "string",
            "description": "VC 템플릿을 적용할 VC 타입",
            "example": "VaccinationCredential",
            "uniqueItems": true
          },
          "title": { "type": "string", "description": "VC 템플릿 제목", "example": "VC Template Title" },
          "description": {
            "type": "string",
            "description": "VC 템플릿 설명",
            "example": "this is example description of vc template"
          },
          "properties": {
            "description": "템플릿에 설정할 VC Claim의 key,value",
            "example": [
              { "key": "id", "type": "string" },
              {
                "key": "cliam1",
                "type": "object",
                "properties": { "subClaim1": { "type": "number" }, "subClaim2": { "type": "array" } }
              },
              { "key": "email", "type": "string" },
              { "key": "alumniOf", "type": "string" }
            ],
            "type": "array",
            "items": { "$ref": "#/components/schemas/MetaDataItem" }
          },
          "requiredPropertyKeys": {
            "description": "설정한 claim중 반드시 포함되어야 할 claim의 키 값",
            "example": ["email", "alumniOf"],
            "type": "array",
            "items": { "type": "string" }
          },
          "metaDataType": {
            "description": "해당 템플릿을 적용한 VC 발급을 위해 사용자가 서버에 제출할 메타 데이터 타입 ",
            "example": [
              { "key": "name", "type": "string" },
              { "key": "weight", "type": "number" }
            ],
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": ["credentialType", "properties"]
      },
      "VCTemplateResponseDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "VC템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "credentialType": {
            "type": "string",
            "description": "템플릿에 지정된 VC 타입",
            "example": "VaccinationCredential"
          },
          "isModifiable": { "type": "boolean", "description": "템플릿 수정 가능 여부(VC 발급 여부)", "example": true },
          "createdAt": { "type": "string", "description": "생성일시", "example": "2023-03-27T23:50:40.465Z" },
          "updatedAt": { "type": "string", "description": "마지막 수정 일시", "example": "2023-03-27T23:50:40.465Z" },
          "title": { "type": "string", "description": "VC template title", "example": "VC Template Title" },
          "description": {
            "type": "string",
            "description": "VC 템플릿 설명",
            "example": "this is description of VC template"
          },
          "properties": {
            "description": "템플릿에 설정된 VC Claim의 key,value",
            "example": [
              { "key": "id", "type": "string" },
              {
                "key": "cliam1",
                "type": "object",
                "properties": { "subClaim1": { "type": "number" }, "subClaim2": { "type": "array" } }
              },
              { "key": "email", "type": "string" },
              { "key": "alumniOf", "type": "string" }
            ],
            "type": "array",
            "items": { "$ref": "#/components/schemas/MetaDataItem" }
          },
          "requiredPropertyKeys": {
            "description": "Claim중 반드시 포함되어야 할 claim의 키 값",
            "example": ["email", "alumniOf"],
            "type": "array",
            "items": { "type": "string" }
          },
          "metaDataType": {
            "description": "해당 템플릿을 적용한 VC 발급을 위해 사용자가 서버에 제출할 메타 데이터 타",
            "example": [
              { "key": "name", "type": "string" },
              { "key": "weight", "type": "number" }
            ],
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": ["id", "credentialType", "isModifiable", "createdAt", "updatedAt", "properties", "metaDataType"]
      },
      "UpdateVCTemplateRequestDTO": {
        "type": "object",
        "properties": {
          "credentialType": {
            "type": "string",
            "description": "VC 템플릿을 적용할 VC 타입",
            "example": "VaccinationCredential",
            "uniqueItems": true
          },
          "title": { "type": "string", "description": "VC 템플릿 제목", "example": "VC Template Title" },
          "description": {
            "type": "string",
            "description": "VC 템플릿 설명",
            "example": "this is example description of vc template"
          },
          "properties": {
            "description": "템플릿에 설정할 VC Claim의 key,value",
            "example": [
              { "key": "id", "type": "string" },
              {
                "key": "cliam1",
                "type": "object",
                "properties": { "subClaim1": { "type": "number" }, "subClaim2": { "type": "array" } }
              },
              { "key": "email", "type": "string" },
              { "key": "alumniOf", "type": "string" }
            ],
            "type": "array",
            "items": { "$ref": "#/components/schemas/MetaDataItem" }
          },
          "requiredPropertyKeys": {
            "description": "설정한 claim중 반드시 포함되어야 할 claim의 키 값",
            "example": ["email", "alumniOf"],
            "type": "array",
            "items": { "type": "string" }
          },
          "metaDataType": {
            "description": "해당 템플릿을 적용한 VC 발급을 위해 사용자가 서버에 제출할 메타 데이터 타입 ",
            "example": [
              { "key": "name", "type": "string" },
              { "key": "weight", "type": "number" }
            ],
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": ["properties"]
      },
      "VPTemplatesItem": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "VP 템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "presentationType": { "type": "string", "description": "VP 타입", "example": "VaccinationPresentation" },
          "createdAt": { "type": "string", "description": "생성일시", "example": "2023-03-27T23:50:40.465Z" },
          "updatedAt": { "type": "string", "description": "마지막 수정 일시", "example": "2023-03-27T23:50:40.465Z" }
        },
        "required": ["id", "presentationType", "createdAt", "updatedAt"]
      },
      "VPTemplatesResponseDTO": {
        "type": "object",
        "properties": {
          "templates": {
            "description": "VC 템플릿의 목록",
            "example": [
              {
                "id": "849e1786-b4e9-407e-8d0d-86777770af8a",
                "presentationType": "VaccinationPresentation",
                "createdAt": "2023-03-27T23:50:40.465Z",
                "updatedAt": "2023-03-27T23:50:40.465Z"
              }
            ],
            "type": "array",
            "items": { "$ref": "#/components/schemas/VPTemplatesItem" }
          }
        },
        "required": ["templates"]
      },
      "CreateVPTemplateResponseDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "VP 템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          }
        },
        "required": ["id"]
      },
      "CreateVPTemplateRequestDTO": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "VP 템플릿 설명",
            "example": "this is description of vp template"
          },
          "presentationType": { "type": "string", "description": "VP 타입", "example": "VaccinationPresentation" },
          "credentialTypes": {
            "description": "VP 제출시 포함되어야 할 VC 타입들",
            "example": ["VaccinationCredential"],
            "type": "array",
            "items": { "type": "array" }
          }
        },
        "required": ["presentationType", "credentialTypes"]
      },
      "VPTemplateResponseDTO": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "VP 템플릿 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "presentationType": { "type": "string", "description": "VP 타입", "example": "VaccinationPresentation" },
          "createdAt": { "type": "string", "description": "생성일시", "example": "2023-03-27T23:50:40.465Z" },
          "updatedAt": { "type": "string", "description": "마지막 수정 일시", "example": "2023-03-27T23:50:40.465Z" },
          "description": {
            "type": "string",
            "description": "VP 템플릿 설명",
            "example": "this is description of VC template"
          },
          "credentialTypes": {
            "description": "VP 제출시 포함되어야 할 VC 타입들",
            "example": ["VaccinationCredential"],
            "type": "array",
            "items": { "type": "array" }
          }
        },
        "required": ["id", "presentationType", "createdAt", "updatedAt", "credentialTypes"]
      },
      "UpdateVPTemplateRequestDTO": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "VP 템플릿 설명",
            "example": "this is description of vp template"
          },
          "presentationType": { "type": "string", "description": "VP 타입", "example": "VaccinationPresentation" },
          "credentialTypes": {
            "description": "VP 제출시 포함되어야 할 VC 타입들",
            "example": ["VaccinationCredential"],
            "type": "array",
            "items": { "type": "array" }
          }
        }
      },
      "VCRequestResponseDTO": {
        "type": "object",
        "properties": {
          "issuanceStatus": {
            "type": "string",
            "enum": ["Approved", "Rejected", "Pending"],
            "example": "Approved",
            "description": "요청에 대한 서비스 서버 처리 상태"
          },
          "id": {
            "type": "string",
            "description": "VC 발급 요청 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "credentialType": {
            "type": "string",
            "description": "발급요청한 VC 타입",
            "example": "VaccinationCredential",
            "uniqueItems": true
          },
          "holderDID": {
            "type": "string",
            "description": "Holder(VC 발급 요청자)의 DID",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH"
          },
          "templateId": {
            "type": "string",
            "description": "VC 템플릿의 식별자",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH"
          },
          "createdAt": { "type": "string", "description": "생성일시", "example": "2023-03-27T23:50:40.465Z" },
          "updatedAt": { "type": "string", "description": "마지막 수정 일시", "example": "2023-03-27T23:50:40.465Z" }
        },
        "required": ["issuanceStatus", "id", "credentialType", "holderDID", "templateId", "createdAt", "updatedAt"]
      },
      "VCRequestsResponseDTO": {
        "type": "object",
        "properties": {
          "requests": {
            "description": "발급 요청한(된) VC 요청 리스트",
            "example": [
              {
                "id": "849e1786-b4e9-407e-8d0d-86777770af8a",
                "issuanceStatus": "Pending",
                "credentialType": "VaccinationCredential",
                "createdAt": "2023-03-27T23:50:40.465Z",
                "updatedAt": "2023-03-27T23:50:40.465Z",
                "templateId": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH",
                "holderDID": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH"
              }
            ],
            "type": "array",
            "items": { "$ref": "#/components/schemas/VCRequestResponseDTO" }
          }
        },
        "required": ["requests"]
      },
      "VCPayload": {
        "type": "object",
        "properties": {
          "@context": { "type": "array", "items": { "type": "string" } },
          "id": { "type": "string" },
          "type": { "type": "array", "items": { "type": "string" } },
          "credentialSubject": { "type": "object" },
          "issuanceDate": { "type": "string" },
          "proof": { "type": "object" },
          "issuer": { "type": "string" }
        },
        "required": ["@context", "id", "type", "credentialSubject", "issuanceDate", "proof", "issuer"]
      },
      "CreateRequestVCIssuanceResponseDTO": {
        "type": "object",
        "properties": {
          "issuanceStatus": {
            "type": "string",
            "enum": ["Approved", "Rejected", "Pending"],
            "example": "Approved",
            "description": "요청에 대한 서비스 서버 처리 상태"
          },
          "id": {
            "type": "string",
            "description": "VC 발급 요청 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "vc": {
            "description": "발급된 VC",
            "example": {
              "@context": ["https://www.w3.org/2018/credentials/v1", "https://schema.org"],
              "id": "did:infra:space:5FDseiC76zPek2YYkuyenu4ZgxZ7PUWXt9d19HNB5CaQXt5U",
              "type": ["VerifiableCredential", "VaccinationCredential"],
              "credentialSubject": {
                "id": "did:infra:space:5FswCxP6KdqBX9Xt4tHzs8fExN3ttUd5PNhXLaxbYPhVAENc",
                "테스트": "123",
                "alumniOf": "Example University",
                "email": "test@test.com"
              },
              "issuanceDate": "2023-03-22T06:51:36.019Z",
              "proof": {
                "type": "Sr25519Signature2020",
                "created": "2023-03-22T06:51:36Z",
                "verificationMethod": "did:infra:space:5CfVpNJWhHeeb8EWhwKzUk3phDNtUNigCAjnSBYD7S6MnB6a#keys-1",
                "proofPurpose": "assertionMethod",
                "proofValue": "z2F9qgujwMf8M3SDLgrfoFTfyDkRSbszugRRJEVyD5YgFn7k8VdhGHPRM495trrTt9wcCpAsLjA7G8qKopomEwHoR"
              },
              "issuer": "did:infra:space:5CfVpNJWhHeeb8EWhwKzUk3phDNtUNigCAjnSBYD7S6MnB6a"
            },
            "allOf": [{ "$ref": "#/components/schemas/VCPayload" }]
          }
        },
        "required": ["issuanceStatus", "id", "vc"]
      },
      "CreateRequestVCIssuanceRequestDTO": {
        "type": "object",
        "properties": {
          "credentialType": {
            "type": "string",
            "description": "발급요청한 VC 타입",
            "example": "VaccinationCredential",
            "uniqueItems": true
          },
          "vcTemplateId": {
            "type": "string",
            "description": "VC 템플릿의 식별자",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH"
          },
          "metaData": {
            "description": "서비스가 지정한 VC 발급을 위한 사용자 제출 데이터",
            "example": { "name": "max", "ci": "12834792343" },
            "allOf": [{ "$ref": "#/components/schemas/MetaData" }]
          }
        },
        "required": ["credentialType", "vcTemplateId", "metaData"]
      },
      "VCIssuanceResponseDTO": {
        "type": "object",
        "properties": {
          "issuedVCId": {
            "type": "object",
            "description": "발급수락 한 경우 발급된 VC의 식별자",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH   // or null if reject"
          }
        },
        "required": ["issuedVCId"]
      },
      "VCIssuanceRequestDTO": {
        "type": "object",
        "properties": {
          "issuanceStatus": {
            "type": "string",
            "enum": ["Approved", "Rejected"],
            "description": "발급 상태 값",
            "example": "Approved"
          },
          "vcSubject": {
            "type": "object",
            "description": "(issuanceStatus === 'Approve')발급할 VC의 Subject",
            "example": {
              "id": "did:infra:space:5FswCxP6KdqBX9Xt4tHzs8fExN3ttUd5PNhXLaxbYPhVAENc",
              "alumniOf": "Example University",
              "email": "test@test.com"
            }
          }
        },
        "required": ["issuanceStatus", "vcSubject"]
      },
      "IssuedVCsResponseDTO": {
        "type": "object",
        "properties": {
          "issuedVCs": {
            "description": "발급된 VC 정보",
            "example": [
              {
                "createdAt": "2023-03-27T23:50:40.465Z",
                "id": "did:infra:space:5GUHm8KeFXUKBR9kctm3eafs2tgqK3XxcqsnHtRp2kjSdfDF",
                "holderDID": "did:infra:space:5GUHm8KeFXUKBR9kctm3eafs2tgqK3XxcqsnHtRp2kjSdfDF",
                "credentialType": "VaccinationCredential",
                "requestId": "849e1786-b4e9-407e-8d0d-86777770af8a",
                "issuanceStatus": "issued"
              }
            ],
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": ["issuedVCs"]
      },
      "IssuedVCResponseDTO": {
        "type": "object",
        "properties": {
          "holderDID": {
            "type": "string",
            "description": "VC holder의 DID",
            "example": "did:infra:space:5GUHmboViUqJGzjLMwkL98ZoZxPicDtwqkYrquHbSpJ9sDQH"
          },
          "id": {
            "type": "string",
            "description": "VC 식별자",
            "example": "did:infra:space:5GUHm8KeFXUKBR9kctm3eafs2tgqK3XxcqsnHtRp2kjSdfDF"
          },
          "createdAt": { "type": "string", "description": "생성일시", "example": "2023-03-27T23:50:40.465Z" },
          "credentialType": { "type": "string", "description": "발급된 VC 타입", "example": "VaccinationCredential" },
          "requestId": {
            "type": "string",
            "description": "VC 발급 요청 식별자",
            "example": "849e1786-b4e9-407e-8d0d-86777770af8a"
          },
          "issuanceStatus": { "type": "string", "description": "VC의 발급 상태", "example": "issued" },
          "vc": {
            "description": "발급된 VC",
            "example": {
              "@context": ["https://www.w3.org/2018/credentials/v1", "https://schema.org"],
              "id": "did:infra:space:5FDseiC76zPek2YYkuyenu4ZgxZ7PUWXt9d19HNB5CaQXt5U",
              "type": ["VerifiableCredential", "VaccinationCredential"],
              "credentialSubject": {
                "id": "did:infra:space:5FswCxP6KdqBX9Xt4tHzs8fExN3ttUd5PNhXLaxbYPhVAENc",
                "테스트": "123",
                "alumniOf": "Example University",
                "email": "test@test.com"
              },
              "issuanceDate": "2023-03-22T06:51:36.019Z",
              "proof": {
                "type": "Sr25519Signature2020",
                "created": "2023-03-22T06:51:36Z",
                "verificationMethod": "did:infra:space:5CfVpNJWhHeeb8EWhwKzUk3phDNtUNigCAjnSBYD7S6MnB6a#keys-1",
                "proofPurpose": "assertionMethod",
                "proofValue": "z2F9qgujwMf8M3SDLgrfoFTfyDkRSbszugRRJEVyD5YgFn7k8VdhGHPRM495trrTt9wcCpAsLjA7G8qKopomEwHoR"
              },
              "issuer": "did:infra:space:5CfVpNJWhHeeb8EWhwKzUk3phDNtUNigCAjnSBYD7S6MnB6a"
            },
            "allOf": [{ "$ref": "#/components/schemas/VCPayload" }]
          }
        },
        "required": ["createdAt", "credentialType", "requestId", "issuanceStatus", "vc"]
      }
    }
  }
}
